#Screen dimensions
WIDTH = 1920
HEIGHT = 1080

#Scoring
MINIMUM_SCORE = 0
MAXIMUM_SCORE = 100
STARTING_SCORE = 0

#Assets
ASSET_DIRECTORY_NAME = 'assets'

#Audio assets
INCRAMENT_SCORE_SOUND = 'incramentScore.wav'
DECREMENT_SCORE_SOUND = INCRAMENT_SCORE_SOUND
RESET_SCORE_SOUND = 'resetScore'